line_length: 200
cyclomatic_complexity: 5
file_length:
  warning: 500
  error: 1000
type_body_length:
  - 300 # warning
  - 400 # error
disabled_rules: # rule identifiers to exclude from running
  - superfluous_disable_command
