# https://docs.travis-ci.com/user/reference/osx/
osx_image: xcode12
language: swift
# cache: cocoapods
# podfile: Example/Podfile

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=14.0,name=iPhone 11" SDK="iphonesimulator14.0" POD_LINT="YES" SWIFT_LINT="YES"
    - DESTINATION="OS=13.5,name=iPhone 11" SDK="iphonesimulator14.0" POD_LINT="NO" SWIFT_LINT="NO"
    - DESTINATION="OS=12.4,name=iPhone Xs" SDK="iphonesimulator14.0" POD_LINT="NO" SWIFT_LINT="NO"

before_install:
  - brew install swiftlint
  - pod install --project-directory=Example
  # - gem install cocoapods # Since Travis is not always on latest version
  # - xcodebuild -showsdks
  # - instruments -s devices
  # - xcodebuild -version
  # - xcodebuild -list

script:
  - set -o pipefail && xcodebuild test -workspace Example/McPicker.xcworkspace -scheme McPicker-Example -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty
    # Run `swiftlint` if specified
  - if [ $SWIFT_LINT == "YES" ]; then
      swiftlint;
    fi
    # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
